name: Build PDF Artifacts

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build resumes
        uses: yamlresume/action@v0.2.1
        with:
          resumes: |
            resume.yml
            resume.de.yml
          verbose: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: |
            resume.pdf
            resume.html
            resume.md
            resume.de.pdf
            resume.de.html
            resume.de.md
          retention-days: 7
